version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: patch
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: patch
- package-ecosystem: npm
  directory: "/cli"
  schedule:
    interval: weekly
  commit-message:
    prefix: patch
